export const SUGGESTED_FIELDS = {
  B2B: [
    "Age",
    "Gender",
    "Job title",
    "Industry",
    "Zip code",
    "Department",
    "Employees",
    "Brand",
    "Revenue",
    "Company",
    "Country",
    "Nationality",
    "Household Income",
    "Oppo",
  ],
  B2H: [
    "Patient Age",
    "Caregiver Age",
    "Patient Gender",
    "Caregiver Gender",
    "Disease / Condition",
    "First Diagnosed",
    "Medicine Name",
    "Current Medication",
    "Previous Medication",
    "Treatment Duration",
    "Treatment Response",
    "Side Effects",
    "Other Conditions",
    "Healthcare Provider",
    "Insurance Type",
    "Caregiver Relationship",
    "Treatment Satisfaction",
  ],
  B2C: [
    "Age",
    "Gender",
    "ZIP Code",
    "Country",
    "Nationality",
    "Ethnicity",
    "Household Income",
    "Personal Income",
    "Brand",
    "Company",
    "Occupation",
    "Employment Status",
    "Marital Status",
  ],
} as const;

export type SurveyCategory = "B2B" | "B2H" | "B2C";
